import { GoogleGenAI, Chat } from "@google/genai";
import { AnalysisResult, Language, Market, AnalysisMode } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const MARKET_CONFIG = {
  en: {
    'A_SHARE': 'A-Share (Chinese Stock Market)',
    'US_STOCK': 'US Stock Market (NASDAQ/NYSE)',
    'HK_STOCK': 'Hong Kong Stock Market (HKEX)'
  },
  zh: {
    'A_SHARE': 'A股市场',
    'US_STOCK': '美股市场 (纳斯达克/纽交所)',
    'HK_STOCK': '港股市场'
  }
};

export interface ChatSessionResult {
  analysis: AnalysisResult;
  chat: Chat;
}

export const startStockChat = async (stockCode: string, market: Market, lang: Language, mode: AnalysisMode): Promise<ChatSessionResult> => {
  const modelId = "gemini-2.5-flash";
  const marketName = MARKET_CONFIG[lang][market];
  
  // Get current date
  const now = new Date();
  const dateStr = now.toLocaleDateString(lang === 'en' ? 'en-US' : 'zh-CN', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  // Base Identity
  let systemInstruction = lang === 'en' 
    ? `Act as a senior ${marketName} Quantitative Analyst. Today is ${dateStr}. `
    : `扮演一位资深${marketName}量化分析师。今天是 ${dateStr}。`;

  // Mode Specific Instructions
  if (mode === 'LIVE') {
    systemInstruction += lang === 'en'
      ? `MODE: LIVE INTRADAY. Priority: Find the absolute LATEST REAL-TIME price. Technical indicators (MA/MACD) will be estimates based on the forming candle. Focus on intraday momentum and immediate action.`
      : `当前模式: 实时盘中 (LIVE)。优先级: 获取绝对最新的**实时股价**。请注意今天的K线尚未收盘，技术指标(MA/MACD)基于当前价格估算。重点关注盘中动能和即时操作。`;
  } else {
    systemInstruction += lang === 'en'
      ? `MODE: SNAPSHOT (CLOSE). Priority: Analyze the LAST COMPLETED TRADING DAY (Closing Data). Ignore intraday noise if the market is open. Focus on precise, finalized technical indicators from the last close.`
      : `当前模式: 收盘快照 (SNAPSHOT)。优先级: 分析**上一个完整交易日**的收盘数据。如果当前已开盘，请忽略盘中波动，专注于基于确定的收盘价进行的精准技术面复盘。`;
  }

  // Initial Prompt Construction
  const modePromptEn = mode === 'LIVE' 
    ? `FETCH LIVE DATA: Search for "${stockCode} live price" and "${stockCode} intraday chart".`
    : `FETCH CLOSING DATA: Search for "${stockCode} closing price last trading day" and "${stockCode} historical data".`;

  const modePromptZh = mode === 'LIVE'
    ? `获取实时数据: 搜索 "${stockCode} 实时股价" 和 "${stockCode} 今日分时走势"。`
    : `获取收盘数据: 搜索 "${stockCode} 昨日收盘价" 或 "${stockCode} 上个交易日行情"。`;

  const initialPrompt = lang === 'en' ? `
    Target Stock: ${stockCode}
    Current Date: ${dateStr}
    Analysis Mode: ${mode}
    
    ACTION REQUIRED: ${modePromptEn}
    
    Please perform a comprehensive analysis using Search Grounding.
    
    You MUST structure your response strictly in Markdown format with the following sections:

    # 📊 QUANT REPORT: ${stockCode} (${mode === 'LIVE' ? 'Intraday' : 'Closing Snapshot'})

    ## 1. Market Data Snapshot
    (List Price, Change %, PE, Volume. **Explicitly state: "Data time: [Time/Date]"**.)

    ## 2. Technical Analysis
    (Analyze MA, MACD, KDJ, Bollinger Bands. If LIVE, mention these are dynamic.)

    ## 3. Fundamental News
    (Summarize the top 3 recent news items.)

    ## 4. Quantitative Strategy
    **Signal:** [BUY / SELL / HOLD / WAIT]
    **Confidence:** [0-100]%
    **Risk Level:** [Low / Medium / High]
    
    ## 5. Position Guidance
    (Specific instruction on position sizing.)

    ## 6. Execution Plan & Detailed Setup
    - **Primary Entry Zone:** (Specific price range)
    - **Aggressive/Alternative Entry:** (Breakout level)
    - **Hard Stop Loss:** (Specific price trigger)
    - **Take Profit Target 1:** (Conservative target)
    - **Take Profit Target 2:** (Extended target)
    - **Execution Logic:** (Context/Setup)

    *Disclaimer: This analysis is generated by AI for simulation purposes only.*
    ` : `
    目标股票代码: ${stockCode}
    当前日期: ${dateStr}
    分析模式: ${mode === 'LIVE' ? '实时盘中 (Live)' : '收盘快照 (Snapshot/Close)'}
    
    关键指令: ${modePromptZh}
    
    请利用实时互联网数据（Search Grounding）对该股票进行全面分析。
    
    你必须严格按照以下 Markdown 格式组织你的回答：

    # 📊 量化分析报告: ${stockCode} (${mode === 'LIVE' ? '实时盘中' : '收盘复盘'})

    ## 1. 市场数据快照
    (列出价格, 涨跌幅, PE, 成交量。**必须明确标注: "数据时间: [具体时间/日期]"**。如果是LIVE模式，强调是当前价格；如果是SNAPSHOT模式，强调是收盘价。)

    ## 2. 技术面分析
    (分析均线 MA, MACD, KDJ, 布林带。**重要: 如果是LIVE模式，请注明指标随股价变动；如果是SNAPSHOT模式，基于确定的收盘价分析。**)

    ## 3. 基本面消息
    (总结影响该股票的前3条近期新闻或公告。)

    ## 4. 量化策略
    **信号:** [买入 / 卖出 / 持有 / 观望]
    **置信度:** [0-100]%
    **风险等级:** [低 / 中 / 高]
    
    ## 5. 仓位指导
    (具体的仓位管理建议。)

    ## 6. 精细化交易执行计划
    - **核心建仓区间:** (高胜率价格带)
    - **激进/备选策略:** (如突破关键位追涨)
    - **刚性止损位:** (明确价格)
    - **第一止盈位:** (保守目标)
    - **第二止盈位:** (博弈主升浪的目标价格)
    - **操作细节:** (如："分批低吸", "尾盘确认")

    *免责声明: 本分析由AI生成，仅用于模拟，不构成实际投资建议。*
    `;

  try {
    const chat = ai.chats.create({
      model: modelId,
      config: {
        tools: [{ googleSearch: {} }],
        temperature: 0.1, 
        systemInstruction: systemInstruction,
      },
    });

    const response = await chat.sendMessage({ message: initialPrompt });
    const text = response.text || (lang === 'en' ? "No analysis generated." : "未生成分析结果。");
    
    const groundingChunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];
    const groundingSources = groundingChunks
      .map((chunk) => chunk.web)
      .filter((web) => web !== undefined) as Array<{ uri: string; title: string }>;

    return {
      analysis: {
        rawText: text,
        symbol: stockCode,
        timestamp: new Date().toLocaleTimeString(),
        groundingSources,
      },
      chat: chat
    };
  } catch (error) {
    console.error("Gemini Analysis Error:", error);
    const errorMsg = lang === 'en' 
      ? "Failed to analyze stock data. Please check the stock code and try again."
      : "分析股票数据失败。请检查股票代码并重试。";
    throw new Error(errorMsg);
  }
};

export const sendFollowUpMessage = async (chat: Chat, message: string): Promise<string> => {
  try {
    const response = await chat.sendMessage({ message });
    return response.text;
  } catch (error) {
    console.error("Follow-up Error:", error);
    throw new Error("Failed to process follow-up message.");
  }
};